<?php
declare(strict_types=1);

use Aligent\Pci4Compatibility\ViewModel\Modal;
use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 * @var Modal $viewModel
 */
$viewModel = $block->getViewModel();
$sessionLifetime = $viewModel->getSessionLifetime();
$extendSessionUrl = $viewModel->getExtendSessionUrl();

?>

<div id="session-expire-warning-modal">
    <p class="session-warning-icon">&#x26A0;</p>
    <p id="session-warning-message">
        <?= /* @noEscape */ __(
                'Your session will expire in one minute. ' .
                'Please save your changes or extend your session to continue working.'
        ) ?>
    </p>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag('display:none', '#session-expire-warning-modal'); ?>

<script type="text/x-magento-init">
    {
        "#session-expire-warning-modal": {
            "Aligent_Pci4Compatibility/js/session-expiry-warning": {
                "sessionLifetime": <?= /* @noEscape */ (int)$sessionLifetime ?>,
                "extendSessionUrl": "<?= $escaper->escapeUrl($extendSessionUrl) ?>",
                "formKey": "<?= $escaper->escapeJs($block->getFormKey()) ?>"
            }
        }
    }
</script>
